# ML Pipeline Preparation
Follow the instructions below to help you create your ML pipeline.
### 1. Import libraries and load data from database.
- Import Python libraries
- Load dataset from database with [`read_sql_table`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_table.html)
- Define feature and target variables X and Y

In [1]:
# import libraries
import sys
from sqlalchemy import create_engine
import nltk
nltk.download(['punkt', 'wordnet', 'averaged_perceptron_tagger', 'stopwords'])
import sqlite3
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

import re
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
# load data from database
engine = create_engine('sqlite:///InsertDatabaseName.db')
engine.table_names()
df = pd.read_sql_table('InsertTableName', con=engine)
df = df.fillna(0)
# extract values from X and y
X =  df['message'].values
Y = df.loc[:, 'related':'direct_report']
df.head()

id                                            message  \
0   2  Weather update - a cold front from Cuba that c...   
1   7            Is the Hurricane over or is it not over   
2   8                    Looking for someone but no name   
3   9  UN reports Leogane 80-90 destroyed. Only Hospi...   
4  12  says: west side of Haiti, rest of the country ...   

                                            original   genre  related  \
0  Un front froid se retrouve sur Cuba ce matin. ...  direct      1.0   
1                 Cyclone nan fini osinon li pa fini  direct      1.0   
2  Patnm, di Maryani relem pou li banm nouvel li ...  direct      1.0   
3  UN reports Leogane 80-90 destroyed. Only Hospi...  direct      1.0   
4  facade ouest d Haiti et le reste du pays aujou...  direct      1.0   

   request  offer  aid_related  medical_help  medical_products      ...        \
0      0.0    0.0          0.0           0.0               0.0      ...         
1      0.0    0.0          1.0           0.0               0.0      ...         
2      0.0    0.0          0.0           0.0               0.0      ...         
3      1.0    0.0          1.0           0.0               1.0      ...         
4      0.0    0.0          0.0           0.0               0.0      ...         

   aid_centers  other_infrastructure  weather_related  floods  storm  fire  \
0          0.0                   0.0              0.0     0.0    0.0   0.0   
1          0.0                   0.0              1.0     0.0    1.0   0.0   
2          0.0                   0.0              0.0     0.0    0.0   0.0   
3          0.0                   0.0              0.0     0.0    0.0   0.0   
4          0.0                   0.0              0.0     0.0    0.0   0.0   

   earthquake  cold  other_weather  direct_report  
0         0.0   0.0            0.0            0.0  
1         0.0   0.0            0.0            0.0  
2         0.0   0.0            0.0            0.0  
3         0.0   0.0            0.0            0.0  
4         0.0   0.0            0.0            0.0  

[5 rows x 40 columns]

In [3]:
df['related'].unique()

array([ 1.,  0.])

In [4]:
df.isnull().sum()

id                        0
message                   0
original                  0
genre                     0
related                   0
request                   0
offer                     0
aid_related               0
medical_help              0
medical_products          0
search_and_rescue         0
security                  0
military                  0
child_alone               0
water                     0
food                      0
shelter                   0
clothing                  0
money                     0
missing_people            0
refugees                  0
death                     0
other_aid                 0
infrastructure_related    0
transport                 0
buildings                 0
electricity               0
tools                     0
hospitals                 0
shops                     0
aid_centers               0
other_infrastructure      0
weather_related           0
floods                    0
storm                     0
fire                

In [5]:
Y.isnull().sum()

related                   0
request                   0
offer                     0
aid_related               0
medical_help              0
medical_products          0
search_and_rescue         0
security                  0
military                  0
child_alone               0
water                     0
food                      0
shelter                   0
clothing                  0
money                     0
missing_people            0
refugees                  0
death                     0
other_aid                 0
infrastructure_related    0
transport                 0
buildings                 0
electricity               0
tools                     0
hospitals                 0
shops                     0
aid_centers               0
other_infrastructure      0
weather_related           0
floods                    0
storm                     0
fire                      0
earthquake                0
cold                      0
other_weather             0
direct_report       

### 2. Write a tokenization function to process your text data

In [6]:
def tokenize(text):
    # Normalize text
    text = re.sub(r"[^a-zA-Z0-9]", " ", text.lower())
    
    stop_words = stopwords.words("english")
    
    #tokenize
    words = word_tokenize (text)
    
    #stemming
    stemmed = [PorterStemmer().stem(w) for w in words]
    
    #lemmatizing
    words_lemmed = [WordNetLemmatizer().lemmatize(w) for w in stemmed if w not in stop_words]
   
    return words_lemmed

### 3. Build a machine learning pipeline
This machine pipeline should take in the `message` column as input and output classification results on the other 36 categories in the dataset. You may find the [MultiOutputClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputClassifier.html) helpful for predicting multiple target variables.

In [7]:
pipeline = Pipeline([
        ('vect', CountVectorizer(tokenizer=tokenize)),
        ('tfidf', TfidfTransformer()),
        ('clf', MultiOutputClassifier(estimator=RandomForestClassifier()))
    ])

In [8]:
pipeline.get_params()

{'memory': None,
 'steps': [('vect',
   CountVectorizer(analyzer='word', binary=False, decode_error='strict',
           dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
           lowercase=True, max_df=1.0, max_features=None, min_df=1,
           ngram_range=(1, 1), preprocessor=None, stop_words=None,
           strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
           tokenizer=<function tokenize at 0x7f1605448d08>, vocabulary=None)),
  ('tfidf',
   TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)),
  ('clf',
   MultiOutputClassifier(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
               max_depth=None, max_features='auto', max_leaf_nodes=None,
               min_impurity_decrease=0.0, min_impurity_split=None,
               min_samples_leaf=1, min_samples_split=2,
               min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
               oob_score=False, random_state=None,

### 4. Train pipeline
- Split data into train and test sets
- Train pipeline

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
pipeline.fit(X_train, Y_train)

Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...oob_score=False, random_state=None, verbose=0,
            warm_start=False),
           n_jobs=1))])

### 5. Test your model
Report the f1 score, precision and recall for each output category of the dataset. You can do this by iterating through the columns and calling sklearn's `classification_report` on each.

In [10]:
def display_results(Y_test, Y_pred):
    labels = np.unique(Y_pred)
    confusion_mat = confusion_matrix(Y_test.values.argmax(axis=1), Y_pred.argmax(axis=1),labels=labels)
    accuracy = (Y_pred == Y_test).mean()

    print("Labels:", labels)
    print("Confusion Matrix:\n", confusion_mat)
    print("Accuracy:", accuracy)

In [11]:
def main():
    Y_pred = pipeline.predict(X_test)

    display_results(Y_test, Y_pred)

main()

Labels: [ 0.  1.]
Confusion Matrix:
 [[6395   38]
 [   0    0]]
Accuracy: related                   0.725065
request                   0.819645
offer                     0.995294
aid_related               0.562016
medical_help              0.908456
medical_products          0.947169
search_and_rescue         0.969030
security                  0.982238
military                  0.965842
child_alone               1.000000
water                     0.931380
food                      0.883407
shelter                   0.901776
clothing                  0.984970
money                     0.975406
missing_people            0.987096
refugees                  0.965538
death                     0.948839
other_aid                 0.856839
infrastructure_related    0.925763
transport                 0.950357
buildings                 0.941552
electricity               0.978442
tools                     0.995294
hospitals                 0.989525
shops                     0.994231
aid_centers     

### 6. Improve your model
Use grid search to find better parameters. 

In [12]:
# Improved parameters 
parameters = {
        'clf__estimator__n_estimators': [100, 200],
        'clf__estimator__learning_rate': [0.1, 0.3]
    }
    # new model with improved parameters
cv = GridSearchCV(estimator=pipeline, param_grid=parameters, cv=3)

### 7. Test your model
Show the accuracy, precision, and recall of the tuned model.  

Since this project focuses on code quality, process, and  pipelines, there is no minimum performance metric needed to pass. However, make sure to fine tune your models for accuracy, precision and recall to make your project stand out - especially for your portfolio!

In [13]:
def display_results(Y_test, Y_pred):
    labels = np.unique(Y_pred)
    confusion_mat = confusion_matrix(Y_test.values.argmax(axis=1), Y_pred.argmax(axis=1),labels=labels)
    accuracy = (Y_pred == Y_test).mean()

    print("Labels:", labels)
    print("Confusion Matrix:\n", confusion_mat)
    print("Accuracy:", accuracy)


def main():
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
    pipeline.fit(X_train, Y_train)

    Y_pred = pipeline.predict(X_test)

    display_results(Y_test, Y_pred)

main()

Labels: [ 0.  1.]
Confusion Matrix:
 [[6382   35]
 [   0    0]]
Accuracy: related                   0.708517
request                   0.824199
offer                     0.996660
aid_related               0.572795
medical_help              0.922271
medical_products          0.950053
search_and_rescue         0.969637
security                  0.982541
military                  0.968726
child_alone               1.000000
water                     0.935327
food                      0.885532
shelter                   0.909215
clothing                  0.986337
money                     0.979050
missing_people            0.988614
refugees                  0.967815
death                     0.948990
other_aid                 0.859572
infrastructure_related    0.935479
transport                 0.953393
buildings                 0.942766
electricity               0.976317
tools                     0.995142
hospitals                 0.990284
shops                     0.996964
aid_centers     

### 8. Try improving your model further. Here are a few ideas:
* try other machine learning algorithms
* add other features besides the TF-IDF

### 9. Export your model as a pickle file

In [14]:
model = main()

Labels: [ 0.  1.]
Confusion Matrix:
 [[6412   36]
 [   0    0]]
Accuracy: related                   0.717474
request                   0.819645
offer                     0.994990
aid_related               0.554577
medical_help              0.915743
medical_products          0.942614
search_and_rescue         0.970700
security                  0.979353
military                  0.964324
child_alone               1.000000
water                     0.933050
food                      0.884621
shelter                   0.901624
clothing                  0.984515
money                     0.972370
missing_people            0.987855
refugees                  0.964627
death                     0.950812
other_aid                 0.860483
infrastructure_related    0.932443
transport                 0.955822
buildings                 0.944436
electricity               0.978291
tools                     0.994079
hospitals                 0.987855
shops                     0.995446
aid_centers     

In [15]:
import pickle
pickle.dump(model, open('classifier.pkl', 'wb'))

### 10. Use this notebook to complete `train.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database and export a model based on a new dataset specified by the user.